### DISCUSSION TITLE
Add support for user-defined <iframe> origins via Content-Security-Policy

### DISCUSSION THREAD

**Discussion by KazWolfe** [home-assistant/feature-requests#118] [Core functionality]
### Describe your core improvement

It may be desirable for certain users to embed Home Assistant as an `<iframe>` into other applications, such as wall tablets, SSO providers, or as integrations with other dashboard solutions. This can be done with a theoretical configuration:

```yml
http:
  allowed_iframe_origins:
    - file:
    - https://sso.example.com
    - http://*.myhome.internal
```

This will then generate a `Content-Security-Policy` allowing these frames. For compatibility, it also would make sense to continue shipping `X-Frame-Options` for legacy browsers that may not support CSP.

```
Content-Security-Policy: frame-ancestors file: https://sso.example.com http://*.myhome.internal self;
X-Frame-Options: SAMEORIGIN
```

As (modern) browsers will [ignore `X-Frame-Options` if `frame-ancestors` is set](https://centralcsp.com/articles/frame-ancestor-frame-options), only the specified origins will be permitted.

Users constrained to legacy browsers that [understand `X-Frame-Options`](https://caniuse.com/x-frame-options) but _not_ [CSP's `frame-ancestors`](https://caniuse.com/mdn-http_headers_content-security-policy_frame-ancestors) (a very small subset) would still be able to disable `X-Frame-Options` via the already-existing `use_x_frame_options` header.

### Current limitations

At present, this can only be done by setting [`http.use_x_frame_options`](https://www.home-assistant.io/integrations/http/#use_x_frame_options) to `false`, allowing Home Assistant to embedded by anybody. This, in turn, [re-opens the security vulnerability](https://github.com/home-assistant/core/security/advisories/GHSA-935v-rmg9-44mw) that this feature aimed to close.

### Technical benefits

This allows users more control over when and where `iframe`s can be embedded based on their own risk profiles, and prevents re-opening the full security hole exposed by disabling `X-Frame-Options` outright.

This could (may?) also be used as a launch point to support even more Content-Security-Policy settings through different schemas, e.g.:

```yml
http:
  content_security_policy:
    frame_ancestors:
      - file:
      - https://sso.example.com
      - http://*.myhome.internal
    script_src:  # implicit `self`
      - http://cdn.myhome.internal
```

### Additional context

I'd be happy to take a stab at implementing this via PR, assuming certain design considerations are solidified in a way that satisfies project requirements.
