### DISCUSSION TITLE
ntfy - full support of options

### DISCUSSION THREAD

**Discussion by Elu43** [home-assistant/feature-requests#120] [Integration enhancements]
### Integration name

ntfy

### Link to integration documentation on our website

https://www.home-assistant.io/integrations/ntfy

### Describe the enhancement

Hello,

The new ntfy official integration only supports title and message.

Ntfy.sh is powerful when we can use the other options it has such as :

tags:
priority:
attach:
filename:
click:
actions:
icon:

### Use cases

This would allow us to have nicely formatted/actionable notifications.

Best regards :)

**Comment by github-actions** [comment]
🏷️ I've automatically added the `integration: ntfy` label to help categorize this feature request.

**Reply by tr4nt0r** [reply]
This is already in the making, you can follow this PR to get informed when the feature is added to Home Assistant https://github.com/home-assistant/core/pull/143560

**Reply by tr4nt0r** [reply]
@Elu43 The PR has been merged and the features will be available in the next Home Assistant release. I'm working also on support for button actions, but it's not sure if it will make it into next release.

**Reply by llaumgui** [reply]
@tr4nt0r Thx for your job !

Is it possible to use ntfy like a notify platform ? Like [Apprise ](https://www.home-assistant.io/integrations/apprise#configuration) for exemple :

```
  - name: NOTIFIER_NAME
    platform: apprise
    url: YOUR_APPRISE_URLS
```

Create a syntaxe like that will be nice:

```
  - name: NOTIFIER_NAME
    platform: ntfy
    entity_id: notify.home_assistant
    priority: "5"
    tags:
      - rotating_light
    icon: https://ha.local/local/icons/homeassistant.png
```
