### DISCUSSION TITLE
Time trigger should support ‘day’ too

### DISCUSSION THREAD

**Discussion by hmmbob** [home-assistant/feature-requests#26] [Automations & scripts] [answered]
### Describe the feature

Having the ability to specify a day together with the time would be great.

My use case would be triggering the same automation but at different times based in the day of the week. So, let’s say 08:00 at mon-fri, and 09:00 on sat-sun. Ideally, this would look like:

```yaml
automation:
  - trigger:
    - platform: time
      at: 
        time: "15:32:00"
        day: "mon"
    - platform: time
      at: 
        time: "09:32:00"
        day: "sun"
    - platform: time
      at: 
        time: "12:34:56"
        day: 
          - sat
          - sun
```

While still keeping the option to use the current shorthand at: "15:32:00" as well (we’ll need that anyway for backwards compatibility) and preferably also supporting specifying multiple days of the week, like days: "mon, tue, wed, fri, sun" or so.

### Use cases

My use case would be triggering the same automation but at different times based in the day of the week (weekday vs weekend for example)

### Current workarounds

Workaround is to trigger each day at a certain time, and then have a condition to check for the desired weekday. That's.... unnecessary.
