### DISCUSSION TITLE
Clicking a light group in the UI should turn_on / turn_off, not toggle

### DISCUSSION THREAD

**Discussion by hmmbob** [home-assistant/feature-requests#28] [I'm not sure] [answered]
### Describe your request

I never understood why clicking a `light` group in the UI _toggles_ all lights in the group, instead off _turning them on/off_ (depending on the group state). I'd like groups to actually turn on/off completely, instead of creating/maintaining a weird mixed state by toggling the group members.

### Why the uncertainty?

Not sure if core or UI

### Use cases

I group my {{insert room name}} lights into a light group, but sometimes not all of them are on at the same time as one can also manually switch them. Clicking the group in the UI would turn off those lights that are on, but also turn on the group members that were off before.... Desired behavior is to either turn all of them off (if the group is currently on) or vice versa.

### Anything else?

I actually created a script to fix this behavior, but it should be core functionality if you ask me. It now just behaves weird.

```yaml
  script:
    light_group_toggle_helper:
      alias: Light group toggle helper
      description: "System: Turn all lights in a group on or off based on status of the group"
      icon: mdi:lightbulb-group
      mode: single
      max_exceeded: silent
      fields:
        group:
          description: "The light group to turn on or off"
          example: "group.lampen_eetkamer"
          required: true
      sequence:
        - condition: "{{ true if group is defined and group != none else false }}"
        - if:
            - "{{ is_state(group, 'on') }}"
          then:
            - action: homeassistant.turn_off
              target:
                entity_id: "{{ group }}"
          else:
            - action: homeassistant.turn_on
              target:
                entity_id: "{{ group }}"
```
