### DISCUSSION TITLE
Make automation editor remember selected entities in action

### DISCUSSION THREAD

**Discussion by DutchessNicole** [home-assistant/feature-requests#33] [Automations & scripts] [answered]
### Describe the feature

When I add multiple entities in the media_player_entity_id entity selector for say, `tts.speak`, because I want to have it work on multiple media_player entities, the automation can save and it does work on all selected entities.
However, whenever I then edit this same automation again, the extra selected entities are lost from the automation and only the first one remains.

This means that I constantly have to re-add the media players that should be affected. This should not be the case.

If multiple entities are selected or added in YAML, those should always be kept as is.

### Use cases

example of the action as saved:
```
action: tts.speak
metadata: {}
data:
  cache: true
  media_player_entity_id: 
    - media_player.home_assistant_voice_092047_media_player
    - media_player.home_assistant_voice_092443_media_player
    - media_player.home_assistant_voice_0971ee_media_player
```

What the action looks like after I save and re-open
```
action: tts.speak
metadata: {}
data:
  cache: true
  media_player_entity_id: media_player.home_assistant_voice_092047_media_player
```

### Current workarounds

I manually add the missing entities back into the YAML for the action every edit.

### Anything else?

I don't mind the entity picker not being able to select multiple items, but if a specific selection is saved to an automation section, it should not be altered without the user's input.

I know I can make media_player groups and use those instead, but that would mean I would have to make a specific permutation for each combination of entities, which is a waste of effort.
