### DISCUSSION TITLE
Keep automation trace longer

### DISCUSSION THREAD

**Discussion by khenderick** [home-assistant/feature-requests#43] [Automations & scripts]
### Describe the feature

At this moment the latest N traces for every automation are preserved and can be consulted. This is of great help when debugging certain issues.

I would love to be able to mark certain runs as "important" where there also N amount of traces of those "important" runs are kept.

Example:
```
automation:
  - id: foobar
    ...
    actions:
      - variables:
          # I always put sensors in variables for easier debugging
      # A bunch of actions
      - if:
          - ... # Something strange happens here, maybe a variable has no (expected) value
        then:
          # This is unexpected, I'd like to keep this trace for longer so I can debug what happend
          - important_trace: true
          - stop "foo"
      # Some more actions
      - if:
          - ... # Some situation that indicates further action is not needed
        then:
           # This is "normal" flow, so this trace can be in the last N amount
           - stop "bar"
      # Another bunch of actions
```

### Use cases

The automation for charging my car runs every minute. Based on the current energy flows (consumption, solar production, ...) it decides with what current my car needs to charge. In the beginning of the automation, I put all sensors I wanna use in variables. I then have an action that validates whether these variables have a value and if it's in an expected range. If not, I stop the charging. The sensor might come online again after an hour, and charging resumes. However, when I notice, it's often too late and it's a pain in the ass figuring out what caused the issue as the trace is long gone.

### Current workarounds

I store the cause of issues in input helpers, so I can consult it later
