### DISCUSSION TITLE
Add actions to Markdown card

### DISCUSSION THREAD

**Discussion by Mariusthvdb** [home-assistant/feature-requests#713] [Dashboards & cards]
using Markdown cards as header cards, for their ability of templates and dynamic titles.

would be magic if we could hold or tap the header to navigate away

and be able to do:
```
  - type: markdown
    card_mod: !include /config/dashboard/card_mods/markdown_heading.yaml # add some styling
    content: In 1 oogopslag
    tap_action:
      action: navigate
      navigation_path: /ui-data/samenvatting
    hold_action:
      action: navigate
      navigation_path: /ui-sub-views/samenvatting_groepen
```

as we now have to resort to `custom:button-card` to do the same. The new section heading card is no alternative either, because we can not use dynamic content.

Ofc that would also be magic ;-)
