### DISCUSSION TITLE
Allow OpenThread Border Router Add-on to use tcp:// for adapter

### DISCUSSION THREAD

**Discussion by johannes-z** [home-assistant/feature-requests#75] [Matter & Thread] [answered]
### Describe the enhancement

Several other addons, most commonly Zigbee2MQTT, allow for specifying the adapter not just locally via `/dev/...`, but also remotely via `tcp://...` using `ser2net`. For example, in Z2M I use `tcp://192.168.1.49:20108` to connect to my zigbee adapter.

### Device or feature details

-

### Use cases

This is needed in cases where the computer Home Assistant is running on is at a remote location. For example, I live in an apartment, and my server is in my basement. There is no radio connection between the floor my apartment is on and my basement. Currently I have to rely on `usbip` to forward the matter adapter across my network.

While `usbip` generally works well, it tends to crash every now and then. Neither watchdog nor systemd seem catch/recover from that, so I have to manually issue `usbip attach` commands to re-attach the usb device.

**Comment by TheJulianJES** [comment, marked as answer]
If you enable "Show unused optional configuration options", you'll see a new "Network device" option pop up. You can enter the IP there.
It's `network_device: 192.168.1.10:6638` for YAML.

**Reply by johannes-z** [reply]
Awesome, will try asap. What do I then add to device? It still wants a valid value.

**Reply by tube0013** [reply]
Just pick anything it's just needed to validate the config of the addon > anything not in a collapsed selection has to have a selection the logic in the addon will use the network address over the selected port. also note the addon spawns a socat connection to the rcp device, OTBR doesn't directly support this.

**Reply by johannes-z** [reply]
Thanks, works great. For future reference, if someone else finds this:

Home Assistant OpenThread Border Router Addon config:
```yaml
device: /dev/ttyS0
baudrate: "460800"
flow_control: true
autoflash_firmware: true
otbr_log_level: notice
firewall: true
nat64: false
network_device: 192.168.1.49:20110
```

/etc/ser2net.yaml config on RP4
```yaml
connection: &con03
  accepter: tcp,20110
  connector: serialdev,/dev/serial/by-id/usb-Nabu_Casa_SkyConnect_v1.0...,460800N81,local,nobreak
  options:
    kickolduser: true
    max-connections: 1
```
