### DISCUSSION TITLE
Enable global variables on a trigger

### DISCUSSION THREAD

**Discussion by Mariusthvdb** [home-assistant/feature-requests#95] [Integration enhancements]
### Describe the enhancement

as [discussed in #beta 2025.7](https://discord.com/channels/330944238910963714/427516175237382144/1387765626239713410)

please consider allowing

```
template:
  - trigger:
      trigger: homeassistant
      event: start
    variables: # this is the first (root level)
      important_date: '25-07-2025'
# nothing else, just the variable
```

so we can use

### Example usage

```yaml
{{important_date}}
```

### Current workarounds

currently using `customize:` and set an attribute per entity (mainly sensors), or use custom_templates, which basically are the same as what I am looking for, only way more complex

### Anything else?

this would be related, though requiring sensor entities per trigger.
I ony want to set the global variable, so I can reuse that anywhere else
